config/routes.rb
Rails.application.routes.draw do
  resources :formato_hc_pregunta

  resources :formato_historial_clinicos

  resources :pregunta

  resources :opciones_respuestas_cerradas

  resources :respuestas_cerradas

  resources :cita

  resources :horarios

  resources :sedes

  resources :consultorios

  resources :turnos

  resources :hora_habils

  resources :minutos_habiles

  resources :dia_habils

  resources :usuarios

  resources :specialities

  resources :convenios

  resources :servicios

  resources :pacientes

  devise_for :users

  root 'home#index'

  resources :administracion, only: :index
  resources :dashboard , only: [:index] do
    collection do
      get :fields_user
      get :add_fields_user
    end
  end
  resources :atencion, only: :index
  resources :historial_clinico, only: :index
  resources :siau, only: :index
  resources :enfermeria, only: :index
  resources :medico_general, only: :index
  resources :medico_especialista, only: :index
  resources :admin_system, only: :index
  resources :recepcion, only: :index
  resources :super_user, only: :index
  resources :editar_perfil , only: [:index] do
    collection do
      get :editar_perfil
      get :show_user_data
    end
  end
  resources :verificar_citas , only: [:index] do
    collection do
      get :get_citas
      get :bajar_cita
      get :registros_atencion
      get :get_registros
      get :eliminar_registro
      get :get_registros_atencion
      get :atender_cita
    end
  end

  resources :admin_historial , only: [:index] do
    collection do
      get :crear_historial
      get :get_pacientes
      get :get_formatos_hc
      get :get_formatos_preguntas_cerrada
      get :get_formatos_preguntas_abierta
    end
  end

  get '/acerca-de-nosotros' => 'home#about_us', as: :about_us
  get '/soluciones' => 'home#solutions', as: :solutions
  get '/crear-usuario' => 'home#create_user', as: :create_user
  get '/usuario-admin' => 'home#check_user_admin', as: :check_user_admin
  get '/show_specialities' => 'home#show_specialities', as: :show_specialities
  get '/search_user' => 'usuarios#search_user', as: :search_user

  get '*path' => redirect('/404.html')

end

app/models/citum.rb
class Citum < ActiveRecord::Base
end

app/models/consultorio.rb
class Consultorio < ActiveRecord::Base
  belongs_to :sede
end

app/models/convenio.rb
class Convenio < ActiveRecord::Base
	has_many :pacientes
end

app/models/dia_habil.rb
class DiaHabil < ActiveRecord::Base
end

app/models/hora_habil.rb
class HoraHabil < ActiveRecord::Base
end

app/models/horario.rb
class Horario < ActiveRecord::Base
end

app/models/minutos_habile.rb
class MinutosHabile < ActiveRecord::Base
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	has_many :convenios
end

app/models/preguntum.rb
class Preguntum < ActiveRecord::Base
  belongs_to :respuestas_cerrada
end

app/models/sede.rb
class Sede < ActiveRecord::Base
	has_many :consultorios
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :can_edit_database
  before_action :set_paciente, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pacientes = Paciente.all
    respond_with(@pacientes)
  end

  def show
    respond_with(@paciente)
  end

  def new
    @identidades = DocumentoIdentidad.all
    @paciente = Paciente.new
    respond_with(@paciente)
  end

  def edit
    @identidades = DocumentoIdentidad.all
  end

  def create
    @paciente = Paciente.new(paciente_params)
    @paciente.save
    respond_with(@paciente)
  end

  def update
    @paciente.update(paciente_params)
    respond_with(@paciente)
  end

  def destroy
    @paciente.destroy
    respond_with(@paciente)
  end

  private
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    def paciente_params
      params.require(:paciente).permit(:tipo_documento, :documento, :pri_nombre, :seg_nombre, :pri_apellido, :seg_apellido, :nacimiento, :genero, :direccion, :telefono, :regimen, :num_ficha_sisben, :estado)
    end

    def can_edit_database
      if current_user.role == "Super" || current_user.role == "Administracion"
        return true
      else
        redirect_to root_path
      end
    end
end

app/helpers/atencion_helper.rb
module AtencionHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/helpers/sedes_helper.rb
module SedesHelper
end

app/helpers/siau_helper.rb
module SiauHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/pacientes/_form.html.slim
= form_for @paciente do |f|
  - if @paciente.errors.any?
    #error_explanation
      h2 = "#{pluralize(@paciente.errors.count, "error")} prohibited this paciente from being saved:"
      ul
        - @paciente.errors.full_messages.each do |message|
          li = message

  .container
    .container_forms
      .panel.panel-default
        .panel-heading
          h4 Informacion del Paciente
        .panel-body
          .form
            .field.form-group
              = f.label :Tipo_de_Documento
              = f.select :tipo_documento, options_for_select(@identidades.map{|s| [s.nombre, s.siglas]}), {}, { class: 'form-control selectpicker', placeholder: 'Tipo de Documento' }
            .field.form-group
              = f.label :Documento
              = f.text_field :documento, class: "form-control"
            .field.form-group
              = f.label :Primer_nombre
              = f.text_field :pri_nombre, class: "form-control"
            .field.form-group
              = f.label :Segundo_nombre
              = f.text_field :seg_nombre, class: "form-control"
            .field.form-group
              = f.label :Primer_apellido
              = f.text_field :pri_apellido, class: "form-control"
            .field.form-group
              = f.label :Segundo_apellido
              = f.text_field :seg_apellido, class: "form-control"
            .field.form-group
              = f.label :Feche_de_Nacimiento
              = f.date_select :nacimiento, class: "form-control"
            .field.form-group
              = f.label :Genero
              = f.select :genero, options_for_select(['M','F']), {}, { class: 'form-control selectpicker', placeholder: 'Ingrese el genero del paciente' }
            .field.form-group
              = f.label :Direccion
              = f.text_field :direccion, class: "form-control"
            .field.form-group
              = f.label :Telefono
              = f.text_field :telefono, class: "form-control"
            .field.form-group
              = f.label :Regimen
              = f.select :regimen, options_for_select([['Subsidiado', 1],['Contributivo', 2]]), {}, { class: 'form-control selectpicker', placeholder: 'Regimen' }
            .field.form-group.hide-fields
              = f.label :Numero_de_ficha_del_sisben
              = f.text_field :num_ficha_sisben, class: "form-control"
            .field.form-group
              = f.label :Estado
              = f.select :estado, options_for_select(['A','I']), {}, { class: 'form-control selectpicker', placeholder: 'Estado del paciente' }
            .sign-button
              = f.submit "Enviar"

app/views/pacientes/edit.html.slim
.content-eps-landing-dash
	.title
		.container
			h2  Editar Paciente

.container
  .row-btn
    .btn.btn-default
      = link_to 'Ver', @paciente, target: "blank"
    .btn.btn-default
      = link_to 'Pacientes', pacientes_path, target: "blank"
    .btn.btn-default
      = link_to 'Ir Administracion', admin_system_index_path, target: "blank"

== render 'form'

app/views/pacientes/index.html.slim
.content-eps-landing-dash
  .title
    .container
      h2  Lista de Pacientes

#contacts-form
  .content-contacts-form
    .container
      .row
        .btn.btn-default
          = link_to 'Ir Administracion', admin_system_index_path, target: "blank"
        .new-contact-button.btn.btn-primary
          = link_to 'Nuevo Paciente', new_paciente_path, target: "blank"

        .table-responsive
          table.table.table-striped
            thead
              tr
                th Tipo documento
                th Documento
                th Nombre
                th Fecha Nacimiento
                th Genero
                th Direccion
                th Telefono
                / th Regimen
                / th Numero ficha sisben
                / th Estado
                th colspan="3"

            tbody
              - @pacientes.each do |paciente|
                tr
                  td = paciente.tipo_documento
                  td = paciente.documento
                  td
                    | #{paciente.pri_nombre} #{paciente.seg_nombre} #{paciente.pri_apellido} #{paciente.seg_apellido}
                  td = paciente.nacimiento
                  td
                    - if paciente.genero == "M"
                      | Maculino
                    -else
                      | Femenino
                  td = paciente.direccion
                  td = paciente.telefono
                  / td = paciente.regimen
                  / td = paciente.num_ficha_sisben
                  / td
                  /   - if paciente.estado == "A"
                  /     | Activo
                  /   -else
                  /     | Inactivo
                  td
                    .btn.btn-primary
                      = link_to paciente, target: "blank"
                        i.fa.fa-eye
                  td
                    .btn.btn-success
                      = link_to edit_paciente_path(paciente), target: "blank"
                        i.fa.fa-pencil-square-o
                  td
                    = button_to paciente, method: :delete, data: {:confirm => 'Are you sure?'}, class: "btn btn-danger"
                      i.fa.fa-trash

        br

app/views/pacientes/new.html.slim
.content-eps-landing-dash
	.title
		.container
			h2  Agregar Paciente

.container
	.row-btn
		.btn.btn-default
			= link_to 'Pacientes', pacientes_path, target: "blank"
		.btn.btn-default
			= link_to 'Ir Administracion', admin_system_index_path, target: "blank"

== render 'form'

app/views/pacientes/show.html.slim
.container
  .row-btn
    .btn.btn-default
      = link_to 'Editar', edit_paciente_path(@paciente), target: "blank"
    .btn.btn-default
      = link_to 'Pacientes', pacientes_path, target: "blank"
    .btn.btn-default
      = link_to 'Ir Administracion', admin_system_index_path, target: "blank"

.contact-show
  .content-contact-show
    .intro-text-contact
      .intro-lead-in-contact #{@paciente.pri_nombre} #{@paciente.seg_nombre} #{@paciente.pri_apellido} #{@paciente.seg_apellido}
      .intro-heading-contact
        p
          strong Tipo documento:
          = @paciente.tipo_documento
        p
          strong Documento:
          = @paciente.documento
        p
          strong Nacimiento:
          = @paciente.nacimiento
        p
          strong Genero:
          - if @paciente.genero == "M"
            | Masculino
          -else
            | Femenino
        p
          strong Direccion:
          = @paciente.direccion
        p
          strong Telefono:
          = @paciente.telefono
        p
          strong Regimen:
          = @paciente.regimen
        p
          strong Numero de ficha del Sisben:
          = @paciente.num_ficha_sisben
        p
          strong Estado:
          - if @paciente.estado == "A"
            | Activo
          -else
            | Inactivo