config/routes.rb
Rails.application.routes.draw do
  resources :formato_hc_pregunta

  resources :formato_historial_clinicos

  resources :pregunta

  resources :opciones_respuestas_cerradas

  resources :respuestas_cerradas

  resources :cita

  resources :horarios

  resources :sedes

  resources :consultorios

  resources :turnos

  resources :hora_habils

  resources :minutos_habiles

  resources :dia_habils

  resources :usuarios

  resources :specialities

  resources :convenios

  resources :servicios

  resources :pacientes

  devise_for :users

  root 'home#index'

  resources :administracion, only: :index
  resources :dashboard , only: [:index] do
    collection do
      get :fields_user
      get :add_fields_user
    end
  end
  resources :atencion, only: :index
  resources :historial_clinico, only: :index
  resources :siau, only: :index
  resources :enfermeria, only: :index
  resources :medico_general, only: :index
  resources :medico_especialista, only: :index
  resources :admin_system, only: :index
  resources :recepcion, only: :index
  resources :super_user, only: :index
  resources :editar_perfil , only: [:index] do
    collection do
      get :editar_perfil
      get :show_user_data
    end
  end
  resources :verificar_citas , only: [:index] do
    collection do
      get :get_citas
      get :bajar_cita
      get :registros_atencion
      get :get_registros
      get :eliminar_registro
      get :get_registros_atencion
      get :atender_cita
    end
  end

  resources :admin_historial , only: [:index] do
    collection do
      get :crear_historial
      get :get_pacientes
      get :get_formatos_hc
      get :get_formatos_preguntas_cerrada
      get :get_formatos_preguntas_abierta
    end
  end

  get '/acerca-de-nosotros' => 'home#about_us', as: :about_us
  get '/soluciones' => 'home#solutions', as: :solutions
  get '/crear-usuario' => 'home#create_user', as: :create_user
  get '/usuario-admin' => 'home#check_user_admin', as: :check_user_admin
  get '/show_specialities' => 'home#show_specialities', as: :show_specialities
  get '/search_user' => 'usuarios#search_user', as: :search_user

  get '*path' => redirect('/404.html')

end

app/models/citum.rb
class Citum < ActiveRecord::Base
end

app/models/consultorio.rb
class Consultorio < ActiveRecord::Base
  belongs_to :sede
end

app/models/convenio.rb
class Convenio < ActiveRecord::Base
	has_many :pacientes
end

app/models/dia_habil.rb
class DiaHabil < ActiveRecord::Base
end

app/models/hora_habil.rb
class HoraHabil < ActiveRecord::Base
end

app/models/horario.rb
class Horario < ActiveRecord::Base
end

app/models/minutos_habile.rb
class MinutosHabile < ActiveRecord::Base
end

app/models/opciones_respuestas_cerrada.rb
class OpcionesRespuestasCerrada < ActiveRecord::Base
  belongs_to :respuestas_cerrada
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	has_many :convenios
end

app/models/preguntum.rb
class Preguntum < ActiveRecord::Base
  belongs_to :respuestas_cerrada
end

app/models/sede.rb
class Sede < ActiveRecord::Base
	has_many :consultorios
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/opciones_respuestas_cerradas_controller.rb
class OpcionesRespuestasCerradasController < ApplicationController
  before_filter :authenticate_user!
  before_filter :can_edit_database
  before_action :set_opciones_respuestas_cerrada, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @opciones_respuestas_cerradas = OpcionesRespuestasCerrada.all
    respond_with(@opciones_respuestas_cerradas)
  end

  def show
    respond_with(@opciones_respuestas_cerrada)
  end

  def new
    @respuestas =  RespuestasCerrada.where(estado: "A")
    @opciones_respuestas_cerrada = OpcionesRespuestasCerrada.new
    respond_with(@opciones_respuestas_cerrada)
  end

  def edit
    @respuestas =  RespuestasCerrada.where(estado: "A")
  end

  def create
    @opciones_respuestas_cerrada = OpcionesRespuestasCerrada.new(
      respuestas_cerrada_id: params[:opciones_respuestas_cerrada][:respuestas_cerrada].to_i,
      opcion: params[:opciones_respuestas_cerrada][:opcion],
      estado: params[:opciones_respuestas_cerrada][:estado]
    )
    @opciones_respuestas_cerrada.save
    respond_with(@opciones_respuestas_cerrada)
  end

  def update
    @opciones_respuestas_cerrada.update_attributes(
      respuestas_cerrada_id: params[:opciones_respuestas_cerrada][:respuestas_cerrada].to_i,
      opcion: params[:opciones_respuestas_cerrada][:opcion],
      estado: params[:opciones_respuestas_cerrada][:estado]
    )
    respond_with(@opciones_respuestas_cerrada)
    # @opciones_respuestas_cerrada.update(opciones_respuestas_cerrada_params)
    # respond_with(@opciones_respuestas_cerrada)
  end

  def destroy
    @opciones_respuestas_cerrada.destroy
    respond_with(@opciones_respuestas_cerrada)
  end

  private
    def set_opciones_respuestas_cerrada
      @opciones_respuestas_cerrada = OpcionesRespuestasCerrada.find(params[:id])
    end

    def can_edit_database
      if current_user.role == "Super" || current_user.role == "Administracion"
        return true
      else
        redirect_to root_path
      end
    end

    # def opciones_respuestas_cerrada_params
    #   params.require(:opciones_respuestas_cerrada).permit(:respuestas_cerrada_id, :opcion, :estado)
    # end
end

app/helpers/atencion_helper.rb
module AtencionHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opciones_respuestas_cerradas_helper.rb
module OpcionesRespuestasCerradasHelper
end

app/helpers/sedes_helper.rb
module SedesHelper
end

app/helpers/siau_helper.rb
module SiauHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/opciones_respuestas_cerradas/_form.html.slim
= form_for @opciones_respuestas_cerrada do |f|
  - if @opciones_respuestas_cerrada.errors.any?
    #error_explanation
      h2 = "#{pluralize(@opciones_respuestas_cerrada.errors.count, "error")} prohibited this opciones_respuestas_cerrada from being saved:"
      ul
        - @opciones_respuestas_cerrada.errors.full_messages.each do |message|
          li = message

  .container
    .container_forms
      .panel.panel-default
        .panel-heading
          h4 Opciones de respuesta cerrada
        .panel-body
          .form
            .field.form-group
              = f.label :Respuestas_cerrada
              = f.select :respuestas_cerrada, options_for_select(@respuestas.map{|s| [s.respuesta, s.id]}), {}, { class: 'form-control selectpicker', placeholder: 'Tipo de Documento' }
            .field.form-group
              = f.label :Opcion_de_la_respuesta
              = f.text_field :opcion, class: "form-control"
            .field.form-group
              = f.label :estado
              = f.select :estado, options_for_select(['A','I']), {}, { class: 'form-control selectpicker', placeholder: 'Estado' }
            .sign-button = f.submit "Enviar"

app/views/opciones_respuestas_cerradas/edit.html.slim
.content-eps-landing-dash
	.title
		.container
			h2  Editar Opcion de Respuesta Cerrada

.container
  .row-btn
    .btn.btn-default
      = link_to 'Ver', @opciones_respuestas_cerrada, target: "blank"
    .btn.btn-default
      = link_to 'Opciones de Respuestas', opciones_respuestas_cerradas_path, target: "blank"
    .btn.btn-default
      = link_to 'Ir Administracion', admin_system_index_path, target: "blank"

== render 'form'

app/views/opciones_respuestas_cerradas/index.html.slim
.content-eps-landing-dash
  .title
    .container
      h2  Lista de Respuestas

#contacts-form
  .content-contacts-form
    .container
      .row
        .btn.btn-default
          = link_to 'Ir Administracion', admin_system_index_path, target: "blank"
        .new-contact-button.btn.btn-primary
          = link_to 'Nueva Opcion de Respuesta Cerrada', new_opciones_respuestas_cerrada_path, target: "blank"

        .table-responsive
          table.table.table-striped
            thead
              tr
                th Respuestas cerrada
                th Opcion
                th Estado
                th colspan="3"

            tbody
              - @opciones_respuestas_cerradas.each do |opciones_respuestas_cerrada|
                tr
                  td = opciones_respuestas_cerrada.respuestas_cerrada[:respuesta]
                  td = opciones_respuestas_cerrada.opcion
                  td
                    - if opciones_respuestas_cerrada.estado == "A"
                      | Activo
                    -else
                      | Inactivo
                  td.btn-crud
                    .btn.btn-primary
                      = link_to opciones_respuestas_cerrada, target: "blank"
                        i.fa.fa-eye
                  td.btn-crud
                    .btn.btn-success
                      = link_to edit_opciones_respuestas_cerrada_path(opciones_respuestas_cerrada), target: "blank"
                        i.fa.fa-pencil-square-o
                  td.btn-crud
                    = button_to opciones_respuestas_cerrada, method: :delete, data: {:confirm => 'Are you sure?'}, class: "btn btn-danger"
                      i.fa.fa-trash
        br

app/views/opciones_respuestas_cerradas/new.html.slim
.content-eps-landing-dash
	.title
		.container
			h2  Agregar Opcion de Respuesta

.container
	.row-btn
		.btn.btn-default
			= link_to 'Opciones de Respuestas', opciones_respuestas_cerradas_path, target: "blank"
		.btn.btn-default
			= link_to 'Ir Administracion', admin_system_index_path, target: "blank"

== render 'form'

app/views/opciones_respuestas_cerradas/show.html.slim
.container
  .row-btn
    .btn.btn-default
      = link_to 'Editar', edit_opciones_respuestas_cerrada_path(@opciones_respuestas_cerrada), target: "blank"
    .btn.btn-default
      = link_to 'Opciones de Respuestas', opciones_respuestas_cerradas_path, target: "blank"
    .btn.btn-default
      = link_to 'Ir Administracion', admin_system_index_path, target: "blank"

.contact-show
  .content-contact-show
    .intro-text-contact
      .intro-lead-in-contact RESPUESTA CERRADA
      .intro-heading-contact
				p
					strong Respuestas Cerrada:
					= @opciones_respuestas_cerrada.respuestas_cerrada[:respuesta]
				p
					strong Opcion:
					= @opciones_respuestas_cerrada.opcion
				p
					strong Estado:
					- if @opciones_respuestas_cerrada.estado == "A"
						| Activo
					-else
						| Inactivo