config/routes.rb
Rails.application.routes.draw do
  resources :formato_hc_pregunta

  resources :formato_historial_clinicos

  resources :pregunta

  resources :opciones_respuestas_cerradas

  resources :respuestas_cerradas

  resources :cita

  resources :horarios

  resources :sedes

  resources :consultorios

  resources :turnos

  resources :hora_habils

  resources :minutos_habiles

  resources :dia_habils

  resources :usuarios

  resources :specialities

  resources :convenios

  resources :servicios

  resources :pacientes

  devise_for :users

  root 'home#index'

  resources :administracion, only: :index
  resources :dashboard , only: [:index] do
    collection do
      get :fields_user
      get :add_fields_user
    end
  end
  resources :atencion, only: :index
  resources :historial_clinico, only: :index
  resources :siau, only: :index
  resources :enfermeria, only: :index
  resources :medico_general, only: :index
  resources :medico_especialista, only: :index
  resources :admin_system, only: :index
  resources :recepcion, only: :index
  resources :super_user, only: :index
  resources :editar_perfil , only: [:index] do
    collection do
      get :editar_perfil
      get :show_user_data
    end
  end
  resources :verificar_citas , only: [:index] do
    collection do
      get :get_citas
      get :bajar_cita
      get :registros_atencion
      get :get_registros
      get :eliminar_registro
      get :get_registros_atencion
      get :atender_cita
    end
  end

  resources :admin_historial , only: [:index] do
    collection do
      get :crear_historial
      get :get_pacientes
      get :get_formatos_hc
      get :get_formatos_preguntas_cerrada
      get :get_formatos_preguntas_abierta
    end
  end

  get '/acerca-de-nosotros' => 'home#about_us', as: :about_us
  get '/soluciones' => 'home#solutions', as: :solutions
  get '/crear-usuario' => 'home#create_user', as: :create_user
  get '/usuario-admin' => 'home#check_user_admin', as: :check_user_admin
  get '/show_specialities' => 'home#show_specialities', as: :show_specialities
  get '/search_user' => 'usuarios#search_user', as: :search_user

  get '*path' => redirect('/404.html')

end

app/models/citum.rb
class Citum < ActiveRecord::Base
end

app/models/consultorio.rb
class Consultorio < ActiveRecord::Base
  belongs_to :sede
end

app/models/convenio.rb
class Convenio < ActiveRecord::Base
	has_many :pacientes
end

app/models/dia_habil.rb
class DiaHabil < ActiveRecord::Base
end

app/models/hora_habil.rb
class HoraHabil < ActiveRecord::Base
end

app/models/horario.rb
class Horario < ActiveRecord::Base
end

app/models/minutos_habile.rb
class MinutosHabile < ActiveRecord::Base
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	has_many :convenios
end

app/models/preguntum.rb
class Preguntum < ActiveRecord::Base
  belongs_to :respuestas_cerrada
end

app/models/sede.rb
class Sede < ActiveRecord::Base
	has_many :consultorios
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/atencion_helper.rb
module AtencionHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sedes_helper.rb
module SedesHelper
end

app/helpers/siau_helper.rb
module SiauHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/shared/_footer.slim
.footer class=""
  .container
    .row
      .pull-left
        .footer-details
          ul.list-inline.text-center.links
            li
              = link_to("Acerca de nosotros", about_us_path, target: 'blank')
            li="|"
            li
              = link_to("Soluciones", solutions_path, target: 'blank')
            li="|"
            li
              a href="mailto:eps.majj@gmail.com" Contactanos
          .copyright.text-center.public-show-block
            | © 2015 EPS MAJJ. Todos los derechos reservados.

      .pull-right
        = image_tag("logo.png", alt: "logo")

app/views/shared/_formula_medica.slim
#formulaMedica.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#exampleModalLabel.modal-title Formula Medica
      .modal-body
        form
          .form-group
            label.control-label for="recipient-name" Atencion:
            select.selectpicker.form-control
              option value="" 1
              option value="" 2
              option value="" 3
          .form-group
            label.control-label for="message-text" Codigo del medicamento:
            select.selectpicker.form-control
              option value="" 0933
              option value="" 0934
              option value="" 0934
          .form-group
            label.control-label for="message-text" Prescripcion del medicamento:
            textarea#message-text.form-control
          .form-group
            label.control-label for="message-text" Cantidad:
            input#recipient-name.form-control type="number"
      .modal-footer
        button.btn.btn-danger data-dismiss="modal" type="button"  Cerrar
        button.btn.btn-primary type="button"  Enviar

app/views/shared/_header.slim
header
	.container
		.pull-left.logo-wrapper
			= link_to root_path
				=image_tag "logo.png"
		.pull-right
			.nav.hide-list-header
				ul.principal-navigation
					li
						a.header-link href=""
							i.fa.fa-bars
						ul.sub-menu
							li
								= link_to("Acerca de nosotros", about_us_path, target: 'blank')
							li
								= link_to("Soluciones", solutions_path, target: 'blank')
							li
								a href="mailto:eps.majj@gmail.com" Contactanos
							-if user_signed_in?
								li
									= link_to("Cerrar Sesión", destroy_user_session_path, method: :delete)
								li
									= link_to('Editar Perfil', editar_perfil_index_path, target: 'blank')
							-else
								/li
									/= link_to("Crear Usuario", create_user_path, :class => 'navbar-link', target: 'blank')
								li
									= link_to("Iniciar Sesión", new_user_session_path, :class => 'navbar-link')
			.nav
				ul.principal-navigation
					li
						a.header-link href="" Nuestra EPS
						ul.sub-menu
							li
								= link_to("Acerca de nosotros", about_us_path, target: 'blank')
							li
								= link_to("Soluciones", solutions_path, target: 'blank')
							li
								a href="mailto:eps.majj@gmail.com" Contactanos
					-if user_signed_in?
						/ li
						/ 	= link_to("Dashboard", root_path)
						li
							= link_to("Cerrar Sesión", destroy_user_session_path, method: :delete, class: "header-link")
						li.user
							a.header-link href=""
								strong
									= "#{current_user.first_name} #{current_user.last_name}"
							ul.sub-menu
								li
									= link_to('Edit profile', editar_perfil_index_path, target: 'blank', class: "header-link")
					-else
						/li
							/= link_to("Crear Usuario", create_user_path, :class => 'navbar-link', target: 'blank')
							/ = link_to("Crear Usuario", new_user_registration_path, :class => 'navbar-link')
						li.login-button
							= link_to("Iniciar Sesión", new_user_session_path, :class => 'navbar-link', class: "header-link")
.header-separator

app/views/shared/_incapacidad.slim
#incapacidad.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#exampleModalLabel.modal-title Incapacidad
      .modal-body
        form
          .form-group
            label.control-label for="recipient-name" Atencion:
            select.selectpicker.form-control
              option value="" 1
              option value="" 2
              option value="" 3
          .form-group
            label.control-label for="message-text" Fecha Inicial:
            input#recipient-name.form-control type="date"
          .form-group
            label.control-label for="message-text" Fecha Final:
            input#recipient-name.form-control type="date"
          .form-group
            label.control-label for="message-text" Prescripcion de la Incapacidad:
            textarea#message-text.form-control
      .modal-footer
        button.btn.btn-danger data-dismiss="modal" type="button"  Cerrar
        button.btn.btn-primary type="button"  Enviar

app/views/shared/_medicamentos.slim
#modalMedicamentos.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#exampleModalLabel.modal-title Medicamentos
      .modal-body
        form
          .form-group
            label.control-label for="message-text" Nombre:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Medicamento Pos:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Presentacion Comercial:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Unidad:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Via Administracion:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Principio Activo:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Unidad de Medida:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Formula Farmaceutica:
            input#recipient-name.form-control type="text"
          .form-group
            label.control-label for="message-text" Laboratorio:
            input#recipient-name.form-control type="text"
      .modal-footer
        button.btn.btn-danger data-dismiss="modal" type="button"  Cerrar
        button.btn.btn-primary type="button"  Enviar

app/views/shared/_orden_analisis.slim
#ordenAnalisis.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#exampleModalLabel.modal-title Medicamentos
      .modal-body
        form
          .form-group
            label.control-label for="recipient-name" Atencion:
            select.selectpicker.form-control id=""
              option value="" 1
              option value="" 2
              option value="" 3
          .form-group
            label.control-label for="recipient-name" Servicio:
            select.selectpicker.form-control id=""
              option value="" 1
              option value="" 2
              option value="" 3
          .form-group
            label.control-label for="message-text" Observacion:
            textarea#message-text.form-control
      .modal-footer
        button.btn.btn-danger data-dismiss="modal" type="button"  Cerrar
        button.btn.btn-primary type="button"  Enviar

app/views/shared/_remision.slim
#modalRemision.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#exampleModalLabel.modal-title Incapacidad
      .modal-body
        form
          .form-group
            label.control-label for="recipient-name" Atencion:
            select.selectpicker.form-control
              option value="" 1
              option value="" 2
              option value="" 3
          .form-group
            label.control-label for="recipient-name" Especialidad:
            select.selectpicker.form-control
              option value="" MEDICINA GENERAL
              option value="" PSICOLOGIA
              option value="" ODONTOLOGIA
          .form-group
            label.control-label for="message-text" Motivo de remision:
            textarea#message-text.form-control
      .modal-footer
        button.btn.btn-danger data-dismiss="modal" type="button"  Cerrar
        button.btn.btn-primary type="button"  Enviar