config/routes.rb
Rails.application.routes.draw do
  resources :formato_hc_pregunta

  resources :formato_historial_clinicos

  resources :pregunta

  resources :opciones_respuestas_cerradas

  resources :respuestas_cerradas

  resources :cita

  resources :horarios

  resources :sedes

  resources :consultorios

  resources :turnos

  resources :hora_habils

  resources :minutos_habiles

  resources :dia_habils

  resources :usuarios

  resources :specialities

  resources :convenios

  resources :servicios

  resources :pacientes

  devise_for :users

  root 'home#index'

  resources :administracion, only: :index
  resources :dashboard , only: [:index] do
    collection do
      get :fields_user
      get :add_fields_user
    end
  end
  resources :atencion, only: :index
  resources :historial_clinico, only: :index
  resources :siau, only: :index
  resources :enfermeria, only: :index
  resources :medico_general, only: :index
  resources :medico_especialista, only: :index
  resources :admin_system, only: :index
  resources :recepcion, only: :index
  resources :super_user, only: :index
  resources :editar_perfil , only: [:index] do
    collection do
      get :editar_perfil
      get :show_user_data
    end
  end
  resources :verificar_citas , only: [:index] do
    collection do
      get :get_citas
      get :bajar_cita
      get :registros_atencion
      get :get_registros
      get :eliminar_registro
      get :get_registros_atencion
      get :atender_cita
    end
  end

  resources :admin_historial , only: [:index] do
    collection do
      get :crear_historial
      get :get_pacientes
      get :get_formatos_hc
      get :get_formatos_preguntas_cerrada
      get :get_formatos_preguntas_abierta
    end
  end

  get '/acerca-de-nosotros' => 'home#about_us', as: :about_us
  get '/soluciones' => 'home#solutions', as: :solutions
  get '/crear-usuario' => 'home#create_user', as: :create_user
  get '/usuario-admin' => 'home#check_user_admin', as: :check_user_admin
  get '/show_specialities' => 'home#show_specialities', as: :show_specialities
  get '/search_user' => 'usuarios#search_user', as: :search_user

  get '*path' => redirect('/404.html')

end

app/models/citum.rb
class Citum < ActiveRecord::Base
end

app/models/consultorio.rb
class Consultorio < ActiveRecord::Base
  belongs_to :sede
end

app/models/convenio.rb
class Convenio < ActiveRecord::Base
	has_many :pacientes
end

app/models/dia_habil.rb
class DiaHabil < ActiveRecord::Base
end

app/models/hora_habil.rb
class HoraHabil < ActiveRecord::Base
end

app/models/horario.rb
class Horario < ActiveRecord::Base
end

app/models/minutos_habile.rb
class MinutosHabile < ActiveRecord::Base
end

app/models/paciente.rb
class Paciente < ActiveRecord::Base
	has_many :convenios
end

app/models/preguntum.rb
class Preguntum < ActiveRecord::Base
  belongs_to :respuestas_cerrada
end

app/models/sede.rb
class Sede < ActiveRecord::Base
	has_many :consultorios
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/speciality.rb
class Speciality < ActiveRecord::Base
end

app/models/turno.rb
class Turno < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/dia_habils_controller.rb
class DiaHabilsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :can_edit_database
  before_action :set_dia_habil, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @dia_habils = DiaHabil.all
    respond_with(@dia_habils)
  end

  def show
    respond_with(@dia_habil)
  end

  def new
    # @dia_habil = DiaHabil.new
    # respond_with(@dia_habil)
    redirect_to '/404.html'
  end

  def edit
  end

  def create
    @dia_habil = DiaHabil.new(dia_habil_params)
    @dia_habil.save
    respond_with(@dia_habil)
  end

  def update
    @dia_habil.update(dia_habil_params)
    respond_with(@dia_habil)
  end

  def destroy
    @dia_habil.destroy
    respond_with(@dia_habil)
  end

  private
    def set_dia_habil
      @dia_habil = DiaHabil.find(params[:id])
    end

    def dia_habil_params
      params.require(:dia_habil).permit(:nombre, :estado)
    end

    def can_edit_database
      if current_user.role == "Super" || current_user.role == "Administracion"
        return true
      else
        redirect_to root_path
      end
    end
end

app/helpers/atencion_helper.rb
module AtencionHelper
end

app/helpers/cita_helper.rb
module CitaHelper
end

app/helpers/dia_habils_helper.rb
module DiaHabilsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/horarios_helper.rb
module HorariosHelper
end

app/helpers/sedes_helper.rb
module SedesHelper
end

app/helpers/siau_helper.rb
module SiauHelper
end

app/helpers/turnos_helper.rb
module TurnosHelper
end

app/views/dia_habils/_form.html.slim
= form_for @dia_habil do |f|
  - if @dia_habil.errors.any?
    #error_explanation
      h2 = "#{pluralize(@dia_habil.errors.count, "error")} prohibited this dia_habil from being saved:"
      ul
        - @dia_habil.errors.full_messages.each do |message|
          li = message

  .container
    .container_forms
      .panel.panel-default
        .panel-heading
          h4 Dia
        .panel-body
          .form
            .field.form-group
              = f.label :Nombre
              = f.text_field :nombre, class: "form-control"
            .field.form-group
              = f.label :Estado
              = f.select :estado, options_for_select(['A','I']), {}, { class: 'form-control selectpicker', placeholder: 'Estado' }
            .sign-button = f.submit "Enviar"

app/views/dia_habils/edit.html.slim
.content-eps-landing-dash
	.title
		.container
			h2  Editar Dia

.container
  .row-btn
    .btn.btn-default
      = link_to 'Ver Dia', @dia_habil, target: "blank"
    .btn.btn-default
      = link_to 'Dias', dia_habils_path, target: "blank"
    .btn.btn-default
      = link_to 'Ir Administracion', admin_system_index_path, target: "blank"

= form_for @dia_habil do |f|
  - if @dia_habil.errors.any?
    #error_explanation
      h2 = "#{pluralize(@dia_habil.errors.count, "error")} prohibited this dia_habil from being saved:"
      ul
        - @dia_habil.errors.full_messages.each do |message|
          li = message

  .container
    .container_forms
      .panel.panel-default
        .panel-heading
          h4 Dia
        .panel-body
          .form
            .field.form-group
              = f.label :Nombre
              = f.text_field :nombre, class: "form-control", disabled: "true"
            .field.form-group
              = f.label :Estado
              = f.select :estado, options_for_select(['A','I']), {}, { class: 'form-control selectpicker', placeholder: 'Estado' }
            .sign-button = f.submit "Enviar"

app/views/dia_habils/index.html.slim
.content-eps-landing-dash
  .title
    .container
      h2  Lista de Dias

#contacts-form
  .content-contacts-form
    .container
      .row
        .btn.btn-default
          = link_to 'Ir Administracion', admin_system_index_path, target: "blank"
        - if @reload_button
          .reload.btn.btn-default
            = link_to 'Dias', dia_habils_path, target: "blank"

        / .search-main
        /   .search-right
        /     form action="/search_user"
        /       input.btn.btn-info type="submit" value="Search"
        /       input.form-control type="text" name="name" placeholder="Buscar por nombre"

        .table-responsive
          table.table.table-striped
            thead
              tr
                th Nombre
                th Estado
                th colspan="3"

            tbody
              - @dia_habils.each do |dia_habil|
                tr
                  td.dos_campos_name = dia_habil.nombre
                  td.dos_campos_estado
                    -if dia_habil.estado == "A"
                      | Activo
                    -else
                      | Inactivo
                  td.btn-crud
                    .btn.btn-primary
                      = link_to dia_habil, target: "blank"
                        i.fa.fa-eye
                  td.btn-crud
                    .btn.btn-success
                      = link_to edit_dia_habil_path(dia_habil), target: "blank"
                        i.fa.fa-pencil-square-o
                  / td.btn-crud
                  /   = button_to dia_habil, method: :delete, data: {:confirm => 'Are you sure?'}, class: "btn btn-danger"
                  /     i.fa.fa-trash

        br

app/views/dia_habils/show.html.slim
.container
  .row-btn
    .btn.btn-default
      = link_to 'Editar Dia', edit_dia_habil_path(@dia_habil), target: "blank"
    .btn.btn-default
      = link_to 'Dias', dia_habils_path, target: "blank"
    .btn.btn-default
      = link_to 'Ir Administracion', admin_system_index_path, target: "blank"

.contact-show
  .content-contact-show
    .intro-text-contact
      .intro-lead-in-contact #{@dia_habil.nombre}
      .intro-heading-contact
        p
          strong Estado:
          -if @dia_habil.estado == "A"
          	| Activo
          -else
          	| Inactivo